INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (1, 'AC', 'ACS', 247, 'Ascension Island', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (2, 'AD', 'AND', 376, 'Andorra', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (3, 'AE', 'ARE', 971, 'United Arab Emirates', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (4, 'AF', 'AFG', 93, 'Afghanistan', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (5, 'AG', 'ATG', 1, 'Antigua and Barbuda', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (6, 'AI', 'AIA', 1, 'Anguilla', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (7, 'AL', 'ALB', 355, 'Albania', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (8, 'AM', 'ARM', 374, 'Armenia', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (9, 'AO', 'AGO', 244, 'Angola', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (10, 'AR', 'ARG', 54, 'Argentina', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (11, 'AS', 'ASM', 1, 'American Samoa', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (12, 'AT', 'AUT', 43, 'Austria', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (13, 'AU', 'AUS', 61, 'Australia', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (14, 'AW', 'ABW', 297, 'Aruba', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (15, 'AX', 'ALA', 358, 'Åland Islands', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (16, 'AZ', 'AZE', 994, 'Azerbaijan', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (17, 'BA', 'BIH', 387, 'Bosnia and Herzegovina', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (18, 'BB', 'BRB', 1, 'Barbados', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (19, 'BD', 'BGD', 880, 'Bangladesh', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (20, 'BE', 'BEL', 32, 'Belgium', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (21, 'BF', 'BFA', 226, 'Burkina Faso', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (22, 'BG', 'BGR', 359, 'Bulgaria', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (23, 'BH', 'BHR', 973, 'Bahrain', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (24, 'BI', 'BDI', 257, 'Burundi', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (25, 'BJ', 'BEN', 229, 'Benin', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (26, 'BL', 'BLM', 590, 'Saint Barthélemy', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (27, 'BM', 'BMU', 1, 'Bermuda', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (28, 'BN', 'BRN', 673, 'Brunei', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (29, 'BO', 'BOL', 591, 'Bolivia', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (30, 'BQ', 'BES', 599, 'Bonaire, Sint Eustatius and Saba', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (31, 'BR', 'BRA', 55, 'Brazil', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (32, 'BS', 'BHS', 1, 'Bahamas', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (33, 'BT', 'BTN', 975, 'Bhutan', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (34, 'BW', 'BWA', 267, 'Botswana', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (35, 'BY', 'BLR', 375, 'Belarus', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (36, 'BZ', 'BLZ', 501, 'Belize', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (37, 'CA', 'CAN', 1, 'Canada', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (38, 'CC', 'CCK', 61, 'Cocos Islands', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (39, 'CD', 'COD', 243, 'The Democratic Republic Of Congo', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (40, 'CF', 'CAF', 236, 'Central African Republic', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (41, 'CG', 'COG', 242, 'Congo', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (42, 'CH', 'CHE', 41, 'Switzerland', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (43, 'CI', 'CIV', 225, 'Côte d''Ivoire', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (44, 'CK', 'COK', 682, 'Cook Islands', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (45, 'CL', 'CHL', 56, 'Chile', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (46, 'CM', 'CMR', 237, 'Cameroon', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (47, 'CN', 'CHN', 86, 'China', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (48, 'CO', 'COL', 57, 'Colombia', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (49, 'CR', 'CRI', 506, 'Costa Rica', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (50, 'CU', 'CUB', 53, 'Cuba', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (51, 'CV', 'CPV', 238, 'Cape Verde', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (52, 'CW', 'CUW', 599, 'Curaçao', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (53, 'CX', 'CXR', 61, 'Christmas Island', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (54, 'CY', 'CYP', 357, 'Cyprus', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (55, 'CZ', 'CZE', 420, 'Czech Republic', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (56, 'DE', 'DEU', 49, 'Germany', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (57, 'DJ', 'DJI', 253, 'Djibouti', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (58, 'DK', 'DNK', 45, 'Denmark', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (59, 'DM', 'DMA', 1, 'Dominica', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (60, 'DO', 'DOM', 1, 'Dominican Republic', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (61, 'DZ', 'DZA', 213, 'Algeria', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (62, 'EC', 'ECU', 593, 'Ecuador', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (63, 'EE', 'EST', 372, 'Estonia', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (64, 'EG', 'EGY', 20, 'Egypt', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (65, 'EH', 'ESH', 212, 'Western Sahara', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (66, 'ER', 'ERI', 291, 'Eritrea', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (67, 'ES', 'ESP', 34, 'Spain', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (68, 'ET', 'ETH', 251, 'Ethiopia', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (69, 'FI', 'FIN', 358, 'Finland', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (70, 'FJ', 'FJI', 679, 'Fiji', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (71, 'FK', 'FLK', 500, 'Falkland Islands', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (72, 'FM', 'FSM', 691, 'Micronesia', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (73, 'FO', 'FRO', 298, 'Faroe Islands', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (74, 'FR', 'FRA', 33, 'France', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (75, 'GA', 'GAB', 241, 'Gabon', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (76, 'GB', 'GBR', 44, 'United Kingdom', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (77, 'GD', 'GRD', 1, 'Grenada', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (78, 'GE', 'GEO', 995, 'Georgia', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (79, 'GF', 'GUF', 594, 'French Guiana', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (80, 'GG', 'GGY', 44, 'Guernsey', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (81, 'GH', 'GHA', 233, 'Ghana', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (82, 'GI', 'GIB', 350, 'Gibraltar', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (83, 'GL', 'GRL', 299, 'Greenland', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (84, 'GM', 'GMB', 220, 'Gambia', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (85, 'GN', 'GIN', 224, 'Guinea', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (86, 'GP', 'GLP', 590, 'Guadeloupe', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (87, 'GQ', 'GNQ', 240, 'Equatorial Guinea', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (88, 'GR', 'GRC', 30, 'Greece', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (89, 'GT', 'GTM', 502, 'Guatemala', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (90, 'GU', 'GUM', 1, 'Guam', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (91, 'GW', 'GNB', 245, 'Guinea-Bissau', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (92, 'GY', 'GUY', 592, 'Guyana', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (93, 'HK', 'HKG', 852, 'Hong Kong', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (94, 'HN', 'HND', 504, 'Honduras', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (95, 'HR', 'HRV', 385, 'Croatia', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (96, 'HT', 'HTI', 509, 'Haiti', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (97, 'HU', 'HUN', 36, 'Hungary', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (98, 'ID', 'IDN', 62, 'Indonesia', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (99, 'IE', 'IRL', 353, 'Ireland', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (100, 'IL', 'ISR', 972, 'Israel', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (101, 'IM', 'IMN', 44, 'Isle Of Man', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (102, 'IN', 'IND', 91, 'India', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (103, 'IO', 'IOT', 246, 'British Indian Ocean Territory', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (104, 'IQ', 'IRQ', 964, 'Iraq', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (105, 'IR', 'IRN', 98, 'Iran', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (106, 'IS', 'ISL', 354, 'Iceland', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (107, 'IT', 'ITA', 39, 'Italy', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (108, 'JE', 'JEY', 44, 'Jersey', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (109, 'JM', 'JAM', 1, 'Jamaica', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (110, 'JO', 'JOR', 962, 'Jordan', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (111, 'JP', 'JPN', 81, 'Japan', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (112, 'KE', 'KEN', 254, 'Kenya', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (113, 'KG', 'KGZ', 996, 'Kyrgyzstan', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (114, 'KH', 'KHM', 855, 'Cambodia', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (115, 'KI', 'KIR', 686, 'Kiribati', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (116, 'KM', 'COM', 269, 'Comoros', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (117, 'KN', 'KNA', 1, 'Saint Kitts And Nevis', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (118, 'KP', 'PRK', 850, 'North Korea', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (119, 'KR', 'KOR', 82, 'South Korea', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (120, 'KW', 'KWT', 965, 'Kuwait', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (121, 'KY', 'CYM', 1, 'Cayman Islands', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (122, 'KZ', 'KAZ', 7, 'Kazakhstan', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (123, 'LA', 'LAO', 856, 'Laos', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (124, 'LB', 'LBN', 961, 'Lebanon', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (125, 'LC', 'LCA', 1, 'Saint Lucia', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (126, 'LI', 'LIE', 423, 'Liechtenstein', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (127, 'LK', 'LKA', 94, 'Sri Lanka', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (128, 'LR', 'LBR', 231, 'Liberia', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (129, 'LS', 'LSO', 266, 'Lesotho', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (130, 'LT', 'LTU', 370, 'Lithuania', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (131, 'LU', 'LUX', 352, 'Luxembourg', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (132, 'LV', 'LVA', 371, 'Latvia', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (133, 'LY', 'LBY', 218, 'Libya', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (134, 'MA', 'MAR', 212, 'Morocco', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (135, 'MC', 'MCO', 377, 'Monaco', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (136, 'MD', 'MDA', 373, 'Moldova', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (137, 'ME', 'MNE', 382, 'Montenegro', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (138, 'MF', 'MAF', 590, 'Saint Martin', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (139, 'MG', 'MDG', 261, 'Madagascar', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (140, 'MH', 'MHL', 692, 'Marshall Islands', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (141, 'MK', 'MKD', 389, 'Macedonia', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (142, 'ML', 'MLI', 223, 'Mali', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (143, 'MM', 'MMR', 95, 'Myanmar', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (144, 'MN', 'MNG', 976, 'Mongolia', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (145, 'MO', 'MAC', 853, 'Macao', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (146, 'MP', 'MNP', 1, 'Northern Mariana Islands', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (147, 'MQ', 'MTQ', 596, 'Martinique', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (148, 'MR', 'MRT', 222, 'Mauritania', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (149, 'MS', 'MSR', 1, 'Montserrat', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (150, 'MT', 'MLT', 356, 'Malta', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (151, 'MU', 'MUS', 230, 'Mauritius', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (152, 'MV', 'MDV', 960, 'Maldives', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (153, 'MW', 'MWI', 265, 'Malawi', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (154, 'MX', 'MEX', 52, 'Mexico', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (155, 'MY', 'MYS', 60, 'Malaysia', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (156, 'MZ', 'MOZ', 258, 'Mozambique', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (157, 'NA', 'NAM', 264, 'Namibia', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (158, 'NC', 'NCL', 687, 'New Caledonia', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (159, 'NE', 'NER', 227, 'Niger', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (160, 'NF', 'NFK', 672, 'Norfolk Island', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (161, 'NG', 'NGA', 234, 'Nigeria', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (162, 'NI', 'NIC', 505, 'Nicaragua', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (163, 'NL', 'NLD', 31, 'Netherlands', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (164, 'NO', 'NOR', 47, 'Norway', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (165, 'NP', 'NPL', 977, 'Nepal', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (166, 'NR', 'NRU', 674, 'Nauru', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (167, 'NU', 'NIU', 683, 'Niue', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (168, 'NZ', 'NZL', 64, 'New Zealand', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (169, 'OM', 'OMN', 968, 'Oman', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (170, 'PA', 'PAN', 507, 'Panama', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (171, 'PE', 'PER', 51, 'Peru', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (172, 'PF', 'PYF', 689, 'French Polynesia', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (173, 'PG', 'PNG', 675, 'Papua New Guinea', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (174, 'PH', 'PHL', 63, 'Philippines', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (175, 'PK', 'PAK', 92, 'Pakistan', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (176, 'PL', 'POL', 48, 'Poland', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (177, 'PM', 'SPM', 508, 'Saint Pierre And Miquelon', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (178, 'PR', 'PRI', 1, 'Puerto Rico', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (179, 'PS', 'PSE', 970, 'Palestine', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (180, 'PT', 'PRT', 351, 'Portugal', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (181, 'PW', 'PLW', 680, 'Palau', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (182, 'PY', 'PRY', 595, 'Paraguay', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (183, 'QA', 'QAT', 974, 'Qatar', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (184, 'RE', 'REU', 262, 'Reunion', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (185, 'RO', 'ROU', 40, 'Romania', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (186, 'RS', 'SRB', 381, 'Serbia', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (187, 'RU', 'RUS', 7, 'Russia', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (188, 'RW', 'RWA', 250, 'Rwanda', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (189, 'SA', 'SAU', 966, 'Saudi Arabia', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (190, 'SB', 'SLB', 677, 'Solomon Islands', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (191, 'SC', 'SYC', 248, 'Seychelles', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (192, 'SD', 'SDN', 249, 'Sudan', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (193, 'SE', 'SWE', 46, 'Sweden', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (194, 'SG', 'SGP', 65, 'Singapore', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (195, 'SH', 'SHN', 290, 'Saint Helena', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (196, 'SI', 'SVN', 386, 'Slovenia', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (197, 'SJ', 'SJM', 47, 'Svalbard And Jan Mayen', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (198, 'SK', 'SVK', 421, 'Slovakia', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (199, 'SL', 'SLE', 232, 'Sierra Leone', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (200, 'SM', 'SMR', 378, 'San Marino', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (201, 'SN', 'SEN', 221, 'Senegal', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (202, 'SO', 'SOM', 252, 'Somalia', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (203, 'SR', 'SUR', 597, 'Suriname', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (204, 'SS', 'SSD', 211, 'South Sudan', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (205, 'ST', 'STP', 239, 'Sao Tome And Principe', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (206, 'SV', 'SLV', 503, 'El Salvador', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (207, 'SX', 'SXM', 1, 'Sint Maarten (Dutch part)', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (208, 'SY', 'SYR', 963, 'Syria', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (209, 'SZ', 'SWZ', 268, 'Swaziland', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (210, 'TA', '', 290, 'Tristan da Cunha', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (211, 'TC', 'TCA', 1, 'Turks And Caicos Islands', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (212, 'TD', 'TCD', 235, 'Chad', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (213, 'TG', 'TGO', 228, 'Togo', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (214, 'TH', 'THA', 66, 'Thailand', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (215, 'TJ', 'TJK', 992, 'Tajikistan', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (216, 'TK', 'TKL', 690, 'Tokelau', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (217, 'TL', 'TLS', 670, 'Timor-Leste', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (218, 'TM', 'TKM', 993, 'Turkmenistan', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (219, 'TN', 'TUN', 216, 'Tunisia', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (220, 'TO', 'TON', 676, 'Tonga', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (221, 'TR', 'TUR', 90, 'Turkey', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (222, 'TT', 'TTO', 1, 'Trinidad and Tobago', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (223, 'TV', 'TUV', 688, 'Tuvalu', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (224, 'TW', 'TWN', 886, 'Taiwan', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (225, 'TZ', 'TZA', 255, 'Tanzania', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (226, 'UA', 'UKR', 380, 'Ukraine', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (227, 'UG', 'UGA', 256, 'Uganda', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (228, 'US', 'USA', 1, 'United States', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (229, 'UY', 'URY', 598, 'Uruguay', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (230, 'UZ', 'UZB', 998, 'Uzbekistan', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (231, 'VA', 'VAT', 39, 'Vatican', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (232, 'VC', 'VCT', 1, 'Saint Vincent And The Grenadines', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (233, 'VE', 'VEN', 58, 'Venezuela', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (234, 'VG', 'VGB', 1, 'British Virgin Islands', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (235, 'VI', 'VIR', 1, 'U.S. Virgin Islands', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (236, 'VN', 'VNM', 84, 'Vietnam', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (237, 'VU', 'VUT', 678, 'Vanuatu', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (238, 'WF', 'WLF', 681, 'Wallis And Futuna', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (239, 'WS', 'WSM', 685, 'Samoa', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (240, 'XK', 'KOS', 383, 'Kosovo', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (241, 'YE', 'YEM', 967, 'Yemen', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (242, 'YT', 'MYT', 262, 'Mayotte', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (243, 'ZA', 'ZAF', 27, 'South Africa', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (244, 'ZM', 'ZMB', 260, 'Zambia', null, null);
INSERT INTO public.countries (id, iso, iso3, call_code, name, created_at, updated_at) VALUES (245, 'ZW', 'ZWE', 263, 'Zimbabwe', null, null);
